title: ä¸å‡ä¸å¼ƒ
description: ä»–å’Œå¥¹
baseurl: ""
url: "https://yanqiwuyingxuan.github.io"
lang: zh-CN
markdown: kramdown

# _config.yml
navigation:
  - name: "ğŸ  é¦–é¡µ"
    url: "/"
    meta:
      title: "ä¸»é¡µ"
      description: "ANSELÃ—ELOISA"
  
  - name: "ğŸ“š æ•…äº‹"
    url: "/blog/"
    dropdown:
      - title: "æŠ€æœ¯æ–‡ç« "
        url: "/blog/tech/"
      - title: "ç”Ÿæ´»éšç¬”" 
        url: "/blog/life/"
  
  - name: "ğŸ’¼ æ—¥è®°"
    url: "/projects/"
    badge: "New"
    highlight: true

  - name: "ğŸŒ è¯­è¨€"
    url: "#"
    languages:
      en: "/en/"
      zh: "/zh/"
      ja: "/ja/"
